### ISSUE TITLE
problem compiling and running the game.

### ISSUE THREAD

**Issue by TheEivonz** [kamali-sina/Sins-Virtues-Legacy#17]
Hi, 
i wanted to try out your rpg game earlier today, but it has caused me more headache than i would prefer. 
My programming skills are not up to par at the moment to make the game launch (eventhough i believe that there is just something im missing.

Im getting this error message when i try to compile the project:

Executing task: CMake: build 

Configure failed.

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 
 
I know you specified the "Make" command, but my vscode program defaulted to "Cmake".

Have any ideas as to what i can do? Again, im not really skilled enough to understand all of this.

**Comment by kamali-sina** [comment]
Hi,
Sorry for responding late. I highly recommend using the terminal and the make Make command to compile the game. If you are using a macOS system you can compile it by using "make mac".

good luck!
